ALTER DATABASE SCHEMASUITE_PULLY SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKDATABASE (SCHEMASUITE_PULLY, 1, TRUNCATEONLY)
ALTER DATABASE SCHEMASUITE_PULLY SET RECOVERY FULL WITH NO_WAIT 
GO

ALTER DATABASE SCHEMASUITE_BELMONT SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKDATABASE (SCHEMASUITE_BELMONT, 1, TRUNCATEONLY)
ALTER DATABASE SCHEMASUITE_BELMONT SET RECOVERY FULL WITH NO_WAIT 
GO

ALTER DATABASE SCHEMAFIBER_DATA SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKDATABASE (SCHEMAFIBER_DATA, 1, TRUNCATEONLY)
ALTER DATABASE SCHEMAFIBER_DATA SET RECOVERY FULL WITH NO_WAIT 
GO

ALTER DATABASE SCHEMAFIBER_DATA_V6 SET RECOVERY SIMPLE WITH NO_WAIT
DBCC SHRINKDATABASE (SCHEMAFIBER_DATA_V6, 1, TRUNCATEONLY)
ALTER DATABASE SCHEMAFIBER_DATA_V6 SET RECOVERY FULL WITH NO_WAIT 
GO